name: Build SetUp (Shared)

on: 
  workflow_call:
  
jobs:
  SetUp:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
      #Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
        #Go Lang
    - uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    
    - name: Install plugin
      run: |
        pip install pytest pytest-cov
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
