name: Test Deployment
on:
  workflow_run:
    workflows:
      - "Continuous Integration"
    types:
      - completed

jobs:

  get_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: get the version number from commit message and create issue if not tag
        id: get_version
        run: |
          # Extract version number from the commit message eg. v1.0.0: added feature 2.0
          version_number=$(git log --format=%B -n 1 ${{ github.sha }} | awk '/^v[0-9]+\.[0-9]+\.[0-9]+/{print $1}')
          
          # Debugging: Print version number
          echo "Version Number: $version_number"

          # create an issue for a member to release the code
          if [ -z "$version_number" ]; then
            # Create an issue
            issue_title="Unable to determine version number"
            issue_body="Please create a valid version tag and release. Assigning to @${{ github.actor }}."
            issue_assignee="${{ github.actor }}"
            
            echo "::set-output name=create_issue::true"
            echo "::set-output name=issue_title::${issue_title}"
            echo "::set-output name=issue_body::${issue_body}"
            echo "::set-output name=issue_assignee::${issue_assignee}"
          fi
          
          echo "::set-output name=version_number::${version_number}"
        
  git_release:
    needs: get_version
    name: Release to Git for Deployment
    runs-on: ubuntu-latest
    if: ${{ needs.get_version.outputs.version_number != '' }}

    steps:
      - name: Set environment version
        run: echo "RELEASE_VERSION=${{ needs.get_version.outputs.version_number }}" >> $GITHUB_ENV
  
      - name: Create a release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: Release v${{ env.RELEASE_VERSION }}
          body: |
            Release notes for v${{ env.RELEASE_VERSION }}.
