name: Release Workflow

on:
  push:
    paths:
      - '**/*.py'  # Adjust the path based on your project structure

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      id: version
      set: ${{ steps.bump-version.outputs.version }}

    steps:
      - name: Determine Change Size
        id: determine-change
        run: |
          # Logic to determine change size
          # Example: count the number of lines changed
          CHANGE_SIZE=$(git diff --shortstat $(git describe --tags --abbrev=0)..HEAD | awk '{print $1}')
          if [ $CHANGE_SIZE -gt 10 ]; then
            CHANGE_TYPE="major"
          elif [ $CHANGE_SIZE -gt 0 ]; then
            CHANGE_TYPE="minor"
          else
            CHANGE_TYPE="patch"
          fi
          echo "::set-output name=change-type::$CHANGE_TYPE"
        shell: bash

      - name: Bump Version
        id: bump-version
        run: echo "::set-output name=version::$(awk -F. "{\$3=\$3+1}1" OFS=. <<< "${{ github.event.ref }}" | sed 's/^refs\/tags\///')"

      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump-version.outputs.version }}
          release_name: Release ${{ steps.bump-version.outputs.version }}
          body: "Change Type: ${{ steps.determine-change.outputs.change-type }}"
