# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Continuous Integration

on:
  push:
    branches: 
        - main
    
jobs:
  Build_SetUp:
    name: Build SetUp
    uses: ./.github/workflows/BuildingSetUp.yml
    

  Testing:
    name: Run Test Cases
    needs: Build_SetUp
    runs-on: ubuntu-latest
    steps:
    # Run installation of pytest in Testing
    - name: Check PyTest Installation
      if: ${{ ! needs.Build_SetUp.outputs.pytest_installed }}
      run: pip install pytest
      
    - name: Checkout Codes
      uses: actions/checkout@v4
      with:
        repository: DevOpsTeamB2023/Assignment_Test_CICDPR

    # Retrieve Test Cases
    - name: Use Test Cases
      if: always()
      run: |
        cd $GITHUB_WORKSPACE/testcase
        pytest -v --cov=../sourcecode --junitxml=report.xml

    # Fail Test, Create Issue
    - if: ${{ failure() }}
      name: Create Issue on Failed workflow
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow Workflow name - `${{ github.workflow }}` failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
          assignees: `${{ github.actor }}`

  Test_Results:
    name: Save Test Results
    needs: Testing
    runs-on: ubuntu-latest
    steps:
    - name: Create Test Results Folder
      run: |
        mkdir testresults
        mv testcase/report.xml ./testresults
        # mv report.xml ./testresults

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with: 
        name: testResults
        path: testresults
    
    - name: Download Remote Test Results
      uses: actions/download-artifact@v2
      with:
        name: testResults

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        junit_files: "report.xml"
