name: Pull Request
on:
  pull_request:
  pull_request_review:
    types:
      - submitted
jobs:
  Requests_Build:
    uses: ./.github/workflows/BuildingSetUp.yml

  Requests_AddReviewer:
    name: Adding Reviewer
    needs: Requests_Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Reviewer
        id: toadd_reviewers
        run: |
          AUTHOR=${{ github.event.pull_request.user.login }}
          if [ "$AUTHOR" == "koayyiting" ]; then
            REVIEWERS="ng-zi-yi"
          else
            REVIEWERS="koayyiting"
          fi
          echo "::set-output name=reviewers::$REVIEWERS"

      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ steps.toadd_reviewers.outputs.reviewers }}

  Response_Review:
    name: Approve Review and Merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    
    steps:          
      - name: Get Pull Request Review
        id: get_reviews
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")

          APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | .user.login')
          echo "::set-output name=approved_reviews::$APPROVED_REVIEWS"
          
      - name: Get Pull Request Checks
        uses: actions/checkout@v3
      - uses: actions/get-status-checks@v4
        id: get_checks
        with:
          ref: ${{ github.sha }}

      - name: Check Review Approved and Successful Checks, Merge
        uses: actions/checkout@v3
        if: ${{ steps.get_reviews.outputs.approved_reviews }} >= 1 && ${{ steps.get-checks.outputs.all-checks-passed == 'true' }}
      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          required_labels: ${{ github.context.payload.pull_request.title }}
          title: ${{github.context.payload.pull_request.number}} + " pull request merged"
          merge_method: merge  # Crucial for merging to the set branch
