name: Pull Request

on:
  pull_request:
    branches: [main]
  pull_request_review:
    types:
      - submitted

jobs:
  Requests_Build:
    name: Build and Test for Pull Request
    runs-on: Ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Install plugin
      run: |
        pip install pytest pytest-cov
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check code
      uses: actions/checkout@v4
      with:
        repository: DevOpsTeamB2023/DevOps_Oct2023_TeamB_Assignment

  Requests_AddReviewer:
    needs: Requests_Build
    runs-on: ubuntu-latest
    steps:
    - name: Add Technical Lead Review
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: koayyiting

  Required-Review:
    runs-on: Ubuntu-latest
    steps:
      - name: Required Pull Request Review
        if: github.event_name == 'pull_request_review'
        uses: softprops/action-gh-release-assets@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.before }}
          inputs: '{"label": "approved"}'
