name: Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - review_requested
  pull_request_review:
    types:
      - submitted
      - dismissed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Add Reviewer
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: |
          echo "Adding reviewer..."
          REVIEWER=${{ secrets.koayyiting }}
          GITHUB_TOKEN=$GITHUB_TOKEN jq -n --arg REVIEWER "$REVIEWER" '{"reviewers": ["\($REVIEWER)"]}' | \
            curl -X POST -d @- -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers"

  review:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Wait for Review
        if: github.event_name == 'pull_request_review' && github.event.action == 'submitted'
        run: |
          echo "Review submitted. Checking for approvals..."
          APPROVED=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews" | \
            jq 'map(select(.state == "APPROVED")) | length')

          if [ "$APPROVED" -gt 0 ]; then
            echo "Pull request approved. Ready to merge!"
          else
            echo "Pull request not approved. Please wait for the review to be approved before merging."
            exit 1
          fi

  merge:
    runs-on: ubuntu-latest
    needs: review

    steps:
      - name: Merge Pull Request
        if: github.event_name == 'pull_request_review' && github.event.action == 'submitted' && github.event.review.state == 'approved'
        run: |
          echo "Merging pull request..."
          GITHUB_TOKEN=$GITHUB_TOKEN gh pr merge --number ${{ github.event.pull_request.number }}
