# Triggered by any pull request from repository
name: Pull Request

on:
  pull_request:
  pull_request_review:
    types:
      - submitted

jobs:
  Requests_Build:
    uses: ./.github/workflows/BuildingSetUp.yml # Reusable workflow

  Requests_AddReviewer:
    name: Adding Reviewer
    needs: Requests_Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Reviewer
        id: toadd_reviewers
        # Default Reviewer = Technical Lead | Developer review Technical Lead
        run: |
          AUTHOR=${{ github.event.pull_request.user.login }}
          if [ "$AUTHOR" == "koayyiting" ]; then
            REVIEWERS="ng-zi-yi"
          else
            REVIEWERS="koayyiting"
          fi
          echo "::set-ouput name=reviewers::$REVIEWERS"

      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ steps.toadd_reviewers.outputs.reviewers }}

  Response_Review:
    name: Approve Review and Merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'
    steps:
      - name: Get Review Status
        id: get_reviews
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")

          APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | .user.login')
          echo "::set-output name=approved_reviews::$APPROVED_REVIEWS"

  Merge_Request:
    if: ${{ needs.Response_Review.outputs.approved_reviews }} >= 1
    needs: Response_Review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Check Status
        id: get-status
        uses: danieldeichfuss/get-status@v0.0.10
        with:
          ref: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # #Add automerge label to be able to run pascalgn/automerge-action@v0.16.2 successfully 
      # - uses: actions/checkout@v4
      # - name: Label Pull Request as automerge
      #   uses: actions/labeler@v4
      #   with:
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: automerge
      #     pr-number: ${{ github.event.pull_request.number }}

      # - uses: actions/checkout@v4
      # - name: Auto Merge Pull Request
      #   if: ${{ steps.get-status.outputs.all-checks-completed == 'true' && steps.get-status.outputs.all-checks-passed == 'true' }}
      #   uses: "pascalgn/automerge-action@v0.16.2"
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #   with:
      #     required_labels: ${{ github.context.payload.pull_request.title }}
      #     title: ${{ github.event.pull_request.number }} + " pull request merged"
      #     merge_method: merge

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository -y https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh
      
      - name: Merge pull request
        if: ${{ steps.get-status.outputs.all-checks-completed == 'true' && steps.get-status.outputs.all-checks-passed == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "Merging pull request $pr_number"
          gh pr merge $pr_number --auto --merge
