#Triggered by any pull reques from repository
name: Pull Request

on:
  pull_request:
  pull_request_review:
    types:
      - submitted

jobs:
  Requests_Build:
    uses: ./.github/workflows/BuildingSetUp.yml #resuable workflow

  Requests_AddReviewer:
    name: Adding Reviewer
    needs: Requests_Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Reviewer
        id: toadd_reviewers
        #Default Reviewer = Technical Lead | Developer review Technical Lead
        run: |
          AUTHOR=${{ github.event.pull_request.user.login }}
          if [ "$AUTHOR" == "koayyiting" ]; then
            REVIEWERS="ng-zi-yi"
          else
            REVIEWERS="koayyiting"
          fi
          echo "::set-output name=reviewers::$REVIEWERS"

      - name: Add Reviewers
        uses: madrapps/add-reviewers@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: ${{ steps.toadd_reviewers.outputs.reviewers }}

  Response_Review:
    name: Approve Review and Merge
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review'

    steps:
      - name: Get Review Status
        id: get_reviews
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVIEWS=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/reviews")

          APPROVED_REVIEWS=$(echo "$REVIEWS" | jq -r '.[] | select(.state == "APPROVED") | .user.login')
          echo "::set-output name=approved_reviews::$APPROVED_REVIEWS"

      - name: Get Check Status
        id: get_checks
        uses: actions/get-status-checks@v7.2.4
        with:
          ref: ${{ github.sha }}

      - name: Merge Action
        if: ${{ steps.get_reviews.outputs.approved_reviews }} >= 1 && steps.get_checks.outputs.checks
        run: |
          # Replace this with your actual merging logic
          echo "Merging pull request..."
          # ... your commands to merge the pull request

      - uses: pascalgn/automerge-action@v15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          required_labels: ${{ github.context.payload.pull_request.title }}
          title: ${{github.context.payload.pull_request.number}} + " pull request merged"
          merge_method: merge
