name: Pull Request
on:
  pull_request:
    branches: [main]
  pull_request_review:
    types:
      - submitted
jobs:
  Requests_Build:
    name: Build and Test for Pull Request
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install plugin
      run: |
        pip install pytest pytest-cov
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check code
      uses: actions/checkout@v4
      with:
        repository: DevOpsTeamB2023/Assignment_Test_CICDPR

  Requests_AddReviewer:
    name: To Be Reviewed by Technical Lead
    needs: Requests_Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
    - name: Add Reviewer
      uses: madrapps/add-reviewers@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: koayyiting

  Required_Review:
    name: Approval by Technical Lead
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    steps:
      - name: Wait for review
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const reviews = await github.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const approvedReviews = reviews.data.filter((review) => review.state === 'APPROVED');
            if (approvedReviews.length < 1) {
              core.setFailed('Pull request must be approved by Technical Lead before merging.');
            }
        
